common:
  namespace: todoapp

todoapp:
  image:
    name: todoapp
    repository: ikulyk404/todoapp
    version: 4.0.1

  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1

  secrets:
    SECRET_KEY: "@e2(yx)v&tgh3_s=0yja-i!dpebxsz^dg47x)-k&kq_3zf*9e*"
    DB_NAME: "app_db"
    DB_USER: "app_user"
    DB_PASSWORD: "1234"
    DB_HOST: "mysql-0.mysql.mysql.svc.cluster.local"

  resources:
    requests:
      memory: "256Mi"
      cpu: "150m"
    limits:
      memory: "256Mi"
      cpu: "150m"

  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      weight: 1
      key: app
      operator: In
      values:
        - kube2py

  hpa:
    minReplicas: 2
    maxReplicas: 5
    cpu:
      averageUtilization: 70
    memory:
      averageUtilization: 70

  pv:
    capacity:
      storage: 1Gi

  pvc:
    resources:
      requests:
        storage: 1Gi

  rbac:
    service_account:
      name: secrets-reader
    role:
      name: secrets-reader
      resources:
        - secrets
      verbs:
        - get
        - watch
        - list
    role_binding:
      name: secrets-reader-binding
